### ISSUE TITLE
Order Hardware parts and track 

### ISSUE THREAD

**Issue by jassjagga** [jassjagga/Capstone-Project-summer_2020#2]
The second task is to order hardware parts and keep track is will get all these parts on time.
1. Moh will be studying the wall parts in detail for the presentation.
2. Bibin will start working on the schematics.

**Comment by Mohsidhu** [comment]
[hardware.pptx](https://github.com/jassjagga/Capstone-Project-summer_2020/files/4852545/hardware.pptx)

**Comment by mikeshams** [comment]
Notify me when receiving other components
Add Built In ADC to BBB features in your ppt file
