### ISSUE TITLE
Schematic Design of hardware 

### ISSUE THREAD

**Issue by BibinBabu94** [jassjagga/Capstone-Project-summer_2020#4]

**Comment by mikeshams** [comment]
1. How to share your screen on Adobe Connect when working with Linux?

**Comment by BibinBabu94** [comment]
We could use Team viewer to share our work on Linux.
For sharing we should install Linux supported Team Viewer on one laptop and also install on the other laptop with windows version.
Logging from the laptop which uses windows OS and then we could copy and paste the ID and password to our Team viewer in Linux platform, the password generated are unique and is randomly generated.
And as the final step we should share the screen from our windows laptop and start working.
